### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by caviri** [swiss-territorial-data-lab/treedet-toolkit#2]
Hello, 

First of all, thanks for making this exciting work open-source. I want to test it. Do you know if the data used for training open? If so, where can I find it? 

I have been checking this data source from swissSURFACE but the resolution doesn't seem enough for tree segmentation. 

https://www.swisstopo.admin.ch/en/geodata/height/surface3d.html#musterdaten

Is this the data source that you have been using? 

Thanks beforehand,
Carlos

**Comment by acerioni** [comment]
Thanks @caviri for your interest in our work!

We used [this point clouds dataset](https://ge.ch/sitg/fiche/1544), which is released by the Canton of Geneva (my employer) under Open Data terms. I can help you getting that dataset, if you need it. As far as ground-truth data is concerned, we used a curated subset of [this other dataset](https://ge.ch/sitg/fiche/4571), plus some other data which were collected on purpose for [this project](https://tech.stdl.ch/PROJ-TREEDET/). If you wish, I can check whether those data are shareable, too.

Best,
Alessandro

**Comment by caviri** [comment]
Thank you a lot for the answer @acerioni. I just found time to check this now. This is a side project, and I only have a little time to dedicate to it. Nevertheless,  I will try to replicate the pipeline by using the point cloud dataset available on the first link you shared. Thank you again.
